import { Link, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import api from '../../utils/axiosConfig';
import { formatPrice } from '../../utils/formatPrice';
import { getImageUrl } from '../../utils/imageUrl';

export default function OrderDetail() {
  const { id } = useParams();
  const { data, isLoading, isError } = useQuery({ queryKey: ['order', id], queryFn: () => api.get(`/orders/${id}`).then(({ data: response }) => response.order), enabled: Boolean(id) });
  if (isLoading) return <p aria-busy="true">Chargement de la commande…</p>;
  if (isError || !data) return <p role="alert">Commande introuvable ou accès refusé.</p>;
  return <section className="max-w-4xl"><Link to="/profil/commandes" className="text-sm underline">Retour à mes commandes</Link><header className="mt-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-heading text-3xl">{data.orderNumber}</h1><p className="mt-2 text-sm text-[var(--gray)]">Passée le {new Intl.DateTimeFormat('fr-MA', { dateStyle: 'long', timeStyle: 'short' }).format(new Date(data.createdAt))}</p></div><span className="rounded bg-[var(--primary-light)] px-3 py-2 text-sm font-semibold capitalize text-[var(--primary)]">{data.status}</span></header><div className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="rounded border border-[var(--border)] bg-white"><h2 className="border-b border-[var(--border)] p-5 font-heading text-2xl">Articles</h2><ul className="divide-y divide-[var(--border)]">{data.items.map((item) => <li key={item.id} className="flex gap-4 p-5"><div className="h-20 w-16 shrink-0 bg-[#F5F5F5]">{item.image && <img src={getImageUrl(item.image)} alt="" className="h-full w-full object-cover" />}</div><div className="flex-1"><p className="font-medium">{item.name}</p><p className="mt-1 text-sm text-[var(--gray)]">Quantité : {item.quantity} × {formatPrice(item.unitPrice)}</p></div><p className="font-semibold">{formatPrice(item.lineTotal)}</p></li>)}</ul></section><aside className="space-y-6"><section className="rounded border border-[var(--border)] bg-white p-5"><h2 className="font-heading text-xl">Livraison</h2><p className="mt-3 text-sm leading-6">{data.shippingFullName}<br />{data.shippingPhone}<br />{data.shippingAddressLine1}<br />{data.shippingCity}{data.shippingPostalCode ? `, ${data.shippingPostalCode}` : ''}</p></section><section className="rounded bg-[var(--dark)] p-5 text-white"><h2 className="font-heading text-xl">Total</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>Sous-total</dt><dd>{formatPrice(data.subtotal)}</dd></div><div className="flex justify-between"><dt>Livraison</dt><dd>{formatPrice(data.deliveryFee)}</dd></div><div className="flex justify-between border-t border-white/20 pt-3 text-base font-bold"><dt>Total</dt><dd>{formatPrice(data.total)}</dd></div></dl></section></aside></div><section className="mt-8 rounded border border-[var(--border)] bg-white p-5"><h2 className="font-heading text-xl">Historique</h2><ol className="mt-4 space-y-3">{data.statusHistory.map((entry) => <li key={entry.id} className="text-sm"><span className="font-semibold capitalize">{entry.status}</span> <span className="text-[var(--gray)]">— {new Intl.DateTimeFormat('fr-MA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(entry.changedAt))}</span>{entry.note && <p className="mt-1 text-[var(--gray)]">{entry.note}</p>}</li>)}</ol></section></section>;
}
