import { Link } from 'react-router-dom';
import { AlertCircle, Package, ShoppingBag, TrendingUp } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import api from '../utils/axiosConfig';
import { formatPrice } from '../utils/formatPrice';
import toast from 'react-hot-toast';

function Stat({ label, value, icon }) { return <article className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between text-pink-700">{icon}<span className="text-xs font-semibold uppercase tracking-wider text-gray-500">{label}</span></div><p className="mt-4 text-2xl font-bold text-gray-950">{value}</p></article>; }

export default function AdminDashboard() {
  const query = useQuery({ queryKey: ['admin-dashboard'], queryFn: async () => { const [products, orders] = await Promise.all([api.get('/products', { params: { limit: 50 } }), api.get('/orders', { params: { limit: 20 } })]); return { products: products.data.items, orders: orders.data.items }; } });
  const updateStatus = async (id, status) => { try { await api.patch(`/orders/${id}/status`, { status }); toast.success('Statut mis à jour'); query.refetch(); } catch (error) { toast.error(error.response?.data?.error?.message || 'Transition impossible'); } };
  if (query.isLoading) return <main className="mx-auto max-w-7xl p-6" aria-busy="true">Chargement de l’administration…</main>;
  if (query.isError) return <main className="mx-auto max-w-7xl p-6" role="alert">Impossible de charger l’administration.</main>;
  const { products, orders } = query.data; const revenue = orders.filter((order) => order.status === 'delivered').reduce((sum, order) => sum + order.total, 0);
  return <main className="mx-auto max-w-7xl space-y-8 p-4 md:p-8"><header><p className="text-sm font-medium text-pink-700">LOOKME / Administration</p><h1 className="mt-1 text-3xl font-bold text-gray-950">Tableau de bord</h1></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Revenus livrés" value={formatPrice(revenue)} icon={<TrendingUp aria-hidden="true" />} /><Stat label="Commandes" value={orders.length} icon={<ShoppingBag aria-hidden="true" />} /><Stat label="Produits" value={products.length} icon={<Package aria-hidden="true" />} /><Stat label="Stock faible" value={products.filter((product) => product.stock <= 3).length} icon={<AlertCircle aria-hidden="true" />} /></section><section className="overflow-x-auto rounded-2xl border border-gray-100 bg-white"><div className="flex items-center justify-between p-5"><h2 className="font-semibold">Commandes récentes</h2><Link className="text-sm font-semibold text-pink-700 hover:underline" to="/catalogue">Voir la boutique</Link></div><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-y bg-gray-50 text-xs uppercase tracking-wider text-gray-500"><tr><th className="p-4">Commande</th><th className="p-4">Client</th><th className="p-4">Total</th><th className="p-4">Statut</th></tr></thead><tbody>{orders.map((order) => <tr key={order._id} className="border-b"><td className="p-4 font-medium">{order.orderNumber}</td><td className="p-4">{order.shippingAddress.fullName}</td><td className="p-4">{formatPrice(order.total)}</td><td className="p-4"><label className="sr-only" htmlFor={`status-${order._id}`}>Statut de {order.orderNumber}</label><select id={`status-${order._id}`} value={order.status} onChange={(event) => updateStatus(order._id, event.target.value)} className="rounded border border-gray-300 bg-white p-2"><option value="pending">En attente</option><option value="confirmed">Confirmée</option><option value="shipped">Expédiée</option><option value="delivered">Livrée</option><option value="cancelled">Annulée</option></select></td></tr>)}</tbody></table></section></main>;
}
