import { Link } from 'react-router-dom'
import { AlertCircle, ArrowRight, Package, ShoppingBag, TrendingUp } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import api from '../utils/axiosConfig'
import { formatPrice } from '../utils/formatPrice'

function Stat({ label, value, icon }) { return <article className="rounded-[var(--radius-md)] border border-[var(--border)] bg-white p-5"><div className="flex items-center justify-between text-[var(--primary)]">{icon}<span className="text-xs font-semibold uppercase tracking-[.12em] text-[var(--gray)]">{label}</span></div><p className="mt-5 text-3xl font-semibold">{value}</p></article> }

export default function AdminDashboard() {
  const dashboard = useQuery({ queryKey: ['admin-dashboard'], queryFn: async () => { const [products, orders] = await Promise.all([api.get('/products/admin/all', { params: { limit: 50 } }), api.get('/orders', { params: { limit: 10 } })]); return { products: products.data.items, orders: orders.data.items } } })
  if (dashboard.isLoading) return <main className="p-8" aria-busy="true">Chargement de l’administration…</main>
  if (dashboard.isError) return <main className="p-8" role="alert">Impossible de charger l’administration.</main>
  const { products, orders } = dashboard.data
  const revenue = orders.filter((order) => order.status === 'delivered').reduce((sum, order) => sum + order.total, 0)
  return <main className="mx-auto max-w-7xl space-y-8 p-5 md:p-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--primary)]">LOOKME / Administration</p><h1 className="mt-2 font-heading text-4xl">Tableau de bord</h1></div><Link className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--primary)] underline" to="/admin/products/new">Créer un produit <ArrowRight size={16} /></Link></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Revenus livrés" value={formatPrice(revenue)} icon={<TrendingUp aria-hidden="true" />} /><Stat label="Commandes récentes" value={orders.length} icon={<ShoppingBag aria-hidden="true" />} /><Stat label="Produits" value={products.length} icon={<Package aria-hidden="true" />} /><Stat label="Stock faible" value={products.filter((product) => product.stock <= 3 && product.status === 'active').length} icon={<AlertCircle aria-hidden="true" />} /></section><section className="overflow-x-auto rounded-[var(--radius-md)] border border-[var(--border)] bg-white"><div className="flex items-center justify-between p-5"><h2 className="font-heading text-2xl">Commandes récentes</h2><Link className="text-sm font-semibold text-[var(--primary)] underline" to="/admin/orders">Toutes les commandes</Link></div><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-y bg-black/[.025] text-xs uppercase tracking-[.12em] text-[var(--gray)]"><tr><th className="p-4">Commande</th><th className="p-4">Client</th><th className="p-4">Total</th><th className="p-4">Statut</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-b last:border-0"><td className="p-4 font-medium">{order.orderNumber}</td><td className="p-4">{order.shippingFullName}</td><td className="p-4">{formatPrice(order.total)}</td><td className="p-4 capitalize">{order.status}</td></tr>)}</tbody></table></section></main>
}
