import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Edit3, Plus, Trash2, X } from 'lucide-react'
import toast from 'react-hot-toast'
import api from '../../utils/axiosConfig'

const initial = { name: '', image: '' }

export default function CategoriesManager() {
  const [form, setForm] = useState(initial)
  const [editing, setEditing] = useState(null)
  const client = useQueryClient()
  const categories = useQuery({ queryKey: ['admin-categories'], queryFn: () => api.get('/categories/admin/all').then(({ data }) => data.items) })
  const refresh = () => client.invalidateQueries({ queryKey: ['admin-categories'] })
  const save = useMutation({ mutationFn: (payload) => editing ? api.put(`/categories/${editing}`, payload) : api.post('/categories', payload), onSuccess: () => { refresh(); setForm(initial); setEditing(null); toast.success(editing ? 'Catégorie mise à jour' : 'Catégorie créée') }, onError: (error) => toast.error(error.response?.data?.error?.message || 'Enregistrement impossible') })
  const archive = useMutation({ mutationFn: (id) => api.delete(`/categories/${id}`), onSuccess: () => { refresh(); toast.success('Catégorie archivée') }, onError: (error) => toast.error(error.response?.data?.error?.message || 'Archivage impossible') })
  const edit = (category) => { setEditing(category.id); setForm({ name: category.name, image: category.image || '', status: category.status }) }
  const submit = (event) => { event.preventDefault(); save.mutate({ name: form.name.trim(), image: form.image.trim() || undefined, status: form.status }) }
  const remove = (category) => { if (window.confirm(`Archiver « ${category.name} » ?`)) archive.mutate(category.id) }
  return <main className="mx-auto max-w-6xl p-5 md:p-8"><header><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--primary)]">Catalogue</p><h1 className="mt-2 font-heading text-4xl">Catégories</h1></header>
    <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_340px]"><section className="overflow-x-auto rounded-[var(--radius-md)] border border-[var(--border)] bg-white"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b bg-black/[.025] text-xs uppercase tracking-[.12em] text-[var(--gray)]"><tr><th className="p-4">Catégorie</th><th className="p-4">Produits</th><th className="p-4">Statut</th><th className="p-4"><span className="sr-only">Actions</span></th></tr></thead><tbody>{categories.isLoading ? <tr><td className="p-5" colSpan="4">Chargement…</td></tr> : categories.data?.map((category) => <tr key={category.id} className="border-b last:border-0"><td className="p-4"><div className="flex items-center gap-3">{category.image ? <img src={category.image} alt="" className="h-10 w-10 rounded object-cover" /> : <span className="grid h-10 w-10 place-items-center rounded bg-black/5"><Plus size={16} /></span>}<span className="font-medium">{category.name}</span></div></td><td className="p-4">{category._count?.products ?? 0}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs ${category.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-stone-100 text-stone-600'}`}>{category.status === 'active' ? 'Active' : 'Archivée'}</span></td><td className="p-4"><div className="flex gap-2"><button type="button" aria-label={`Modifier ${category.name}`} onClick={() => edit(category)} className="rounded p-2 hover:bg-black/5"><Edit3 size={17} /></button><button type="button" aria-label={`Archiver ${category.name}`} disabled={category.status === 'archived' || archive.isPending} onClick={() => remove(category)} className="rounded p-2 text-red-700 hover:bg-red-50 disabled:opacity-50"><Trash2 size={17} /></button></div></td></tr>)}</tbody></table>{categories.data?.length === 0 && <p className="p-8 text-center text-[var(--gray)]">Aucune catégorie.</p>}</section>
      <section className="h-fit rounded-[var(--radius-md)] border border-[var(--border)] bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-heading text-2xl">{editing ? 'Modifier' : 'Nouvelle catégorie'}</h2>{editing && <button type="button" aria-label="Annuler la modification" onClick={() => { setEditing(null); setForm(initial) }}><X size={18} /></button>}</div><form className="mt-5 space-y-4" onSubmit={submit}><label className="block text-sm font-medium">Nom<input required value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} className="mt-1 w-full rounded border border-[var(--border)] px-3 py-3 outline-none focus:border-[var(--primary)]" /></label><label className="block text-sm font-medium">URL image <span className="font-normal text-[var(--gray)]">(facultative)</span><input value={form.image} onChange={(event) => setForm((current) => ({ ...current, image: event.target.value }))} className="mt-1 w-full rounded border border-[var(--border)] px-3 py-3 outline-none focus:border-[var(--primary)]" placeholder="https://…" /></label>{editing && <label className="block text-sm font-medium">Statut<select value={form.status} onChange={(event) => setForm((current) => ({ ...current, status: event.target.value }))} className="mt-1 w-full rounded border border-[var(--border)] px-3 py-3 outline-none focus:border-[var(--primary)]"><option value="active">Active</option><option value="archived">Archivée</option></select></label>}<button disabled={save.isPending} className="inline-flex w-full items-center justify-center gap-2 rounded bg-[var(--primary)] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{editing ? <Edit3 size={16} /> : <Plus size={16} />}{save.isPending ? 'Enregistrement…' : editing ? 'Mettre à jour' : 'Créer la catégorie'}</button></form></section>
    </div>
  </main>
}
